#!/bin/sh

project_root=`dirname ${0}`
project_root=`cd ${project_root}/../; pwd`

project_name=`basename ${project_root}`

echo "project name : ${project_name}"
echo "project root : ${project_root}"
